### ISSUE TITLE
SPARQL ask has components? issue specific for FDP to RDF transformation

### ISSUE THREAD

**Issue by marek-dudas** [openbudgets/pipeline-fragments#1]
In the DCV validation:
SPARQL ask has components? Incorrectly fails on 
- using qb:componentAttachment 
  - That might be solved by adding more original DCV rdf definitions, but that makes debugging harder
- Using auxilliary "fdprdf" properties annotations that control the fdptordf transformation

Quick fix: edited the dpu (in my personal pipeline) to check only for component properties linked with qb:dimension or qb:attribute or qb:measure

**Comment by jindrichmynarz** [comment]
Can you share the pipeline to replicate this issue?

As a safe-check, have you applied the DCV validation to data in the normal form? Validation must be preceded by [normalization](https://github.com/openbudgets/pipeline-fragments/blob/master/dcv/dcv_normalization.jsonld), otherwise it doesn't work.

**Comment by marek-dudas** [comment]
It's not an actual issue, it's rather that my DCV data contain additional non-dcv annotations linked for convenience to DCV entities. I already edited the validation pipeline so that it does not fail on this data. That is here http://obeu.vse.cz:9080/#/pipelines/edit/canvas?pipeline=http:%2F%2Fobeu.vse.cz:9080%2Fresources%2Fpipelines%2Fcreated-1463673163706

**Comment by jindrichmynarz** [comment]
Additional non-DCV annotations of observations should be valid. If the validation pipeline reports them as bugs, then the pipeline is buggy.

However, I still don't see the problem. Can you say which integrity constraint fails? As far as I see from the [execution of the pipeline](http://obeu.vse.cz:9080/#/pipelines/edit/canvas?pipeline=http:%2F%2Fobeu.vse.cz:9080%2Fresources%2Fpipelines%2Fcreated-1463673163706&execution=http:%2F%2Fobeu.vse.cz:9080%2Fresources%2Fexecutions%2Fd9cbcd85-be7e-4079-94ce-5da03f073f2f) you provided, no integrity constraint violations are reported.

**Comment by marek-dudas** [comment]
Seems alright when testing now, closing the issue.
