### ISSUE TITLE
DCV Validation - IC19 - missing support for skos:topConceptOf

### ISSUE THREAD

**Issue by ChristianeEngels** [openbudgets/pipeline-fragments#13]
Previously, IC19 was modified to also support "skos:topConceptOf" (which includes "skos:inScheme"), but somehow this has changed again (by accident?) with the last commits.

**Comment by jindrichmynarz** [comment]
Indeed, it seems the support of `skos:topConceptOf` and `skos:hasTopConcept` was unintentionally dropped.
