### ISSUE TITLE
supporting all CSV formats valid in FDP packages

### ISSUE THREAD

**Issue by fathoni** [openbudgets/pipeline-fragments#14]
Hi @marek-dudas , I found an error in the execution of Aragon 2006 Expenditure Budget FDP2RDF Pipeline, stating 'dc confusion'.

This is the highlight of the error from the log:

`
2016-11-22 13:26:47,570 [FDP to RDF] ERROR c.l.e.e.e.EventFactory - componentFailed
com.linkedpipes.etl.executor.api.v1.RdfException: Can't process file: partidas-gastos
	at com.linkedpipes.etl.executor.api.v1.RdfException.componentFailed(RdfException.java:82) ~[api-executor-v1-0.0.0.jar:na]
	at com.linkedpipes.etl.component.api.impl.ExceptionFactoryImpl.failure(ExceptionFactoryImpl.java:17) ~[na:na]
	at com.linkedpipes.plugin.transformer.fdp.FdpToRdf.execute(FdpToRdf.java:262) ~[na:na]
	at com.linkedpipes.etl.component.api.impl.SimpleComponentImpl.execute(SimpleComponentImpl.java:286) ~[na:na]
	at com.linkedpipes.etl.executor.component.ExecuteComponent.run(ExecuteComponent.java:121) ~[executor.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at java.util.Arrays$ArrayList.get(Arrays.java:3841) ~[na:1.8.0_111-internal]
	at com.linkedpipes.plugin.transformer.fdp.Mapper.onRow(Mapper.java:96) ~[na:na]
	at com.linkedpipes.plugin.transformer.fdp.Parser.parse(Parser.java:69) ~[na:na]
	at com.linkedpipes.plugin.transformer.fdp.FdpToRdf.execute(FdpToRdf.java:255) ~[na:na]
	... 3 common frames omitted
2016-11-22 13:26:47,570 [FDP to RDF] ERROR c.l.e.e.e.EventFactory - executionFailed: Component execution failed.
2016-11-22 13:26:47,570 [FDP to RDF] INFO  c.l.e.e.d.DataUnitManager - Saving data unit: OutputFile : http://localhost:8181/resources/pipelines/created-1479718165609/blank/106 ... 

`

The full log is available here: http://localhost:8181/resources/executions/af7116bf-1f43-4384-8577-225f1b33670d/logs , and pipeline is available here: http://localhost:8181/#/pipelines/edit/canvas?pipeline=http:%2F%2Flocalhost:8181%2Fresources%2Fpipelines%2Fcreated-1479718165609&execution=http:%2F%2Flocalhost:8181%2Fresources%2Fexecutions%2Faf7116bf-1f43-4384-8577-225f1b33670d

**Comment by marek-dudas** [comment]
Could you please describe how you execute the pipeline? Do you use the hook in OS-packager to run the pipeline? Are you trying to transform this file: https://github.com/openbudgets/datasets/blob/master/Aragon/2006/raw/Partidas%20Gastos.csv ?

**Comment by fathoni** [comment]
Yes, I tried to use the hook in OS.packager to run the pipeline. And yes, the dataset I am transforming is the Aragon 2006 expenditure as you mentioned. Here is the link to uploaded dataset in OS Packager: http://next.openspending.org/viewer/848b8e447d0dfc798a77ef4f3a7bbcbd:aragon-2006-expenditure-budget

**Comment by marek-dudas** [comment]
Thanks, I was able to run it locally. So there are three non-standard things the pipeline is not prepared for:
- the csv file uses semicolon as a separator, while the CSV library in LP-ETL only supports comma-separated values
- numeric values in the csv uses comma as decimal mark instead of dot
- the csv file has an extra column that is not described in the json descriptor
If I changed all three things manually (removed the extra column, changed the separator and decimal mark, resulting in [partidas-gastos.zip](https://github.com/openbudgets/pipeline-fragments/files/607013/partidas-gastos.zip)), the pipeline runs through and returns valid-looking data.

I can of course implement support for all the three things, but I would focus on the third one as the first two are in my opinion quite generally non-standard.

**Comment by fathoni** [comment]
okay, Marek, thanks for the inspection. In my opinion, the first case is unfortunately also rather common, for example, OpenCoesione dataset which also uses semicolon as separator (For example, here: https://github.com/openbudgets/datasets/blob/master/OpenCoesione/raw/localizzazioni_sample.csv)

**Comment by jakubklimek** [comment]
Actually, the tabular component of Lp-etl has the delimiter as a parameter.
But I guess the problem is in the library used in the FDP2RDF component?

**Comment by pwalsh** [comment]
@marek-dudas CSV parsing most definitely requires a robust CSV parsing library, which handles the multitude of edge cases around delimiters, use of quotes and so one. If you have written something that just splits on commas then many things will break in significant ways.

I'm pretty sure the FDPs produced by OpenSpending hold information such as the delimiter, for use by other backend systems ( @akariv can confirm ). This could be used, for example, to set the delimiter for your parser without having to scan the file and detect it.

**Comment by jakubklimek** [comment]
@pwalsh While I agree that CSV parsing is not trivial, wouldn't it be beneficial to have only true, valid CSV files in FDPs? (There is also the question of encoding, UTF-8 is in the specification, but many other encodings are used etc.) Or do you prefer to have the original data in there even though it is not valid CSV?

**Comment by pwalsh** [comment]
Hey @jakubklimek 

We work with the world as it is, not as we'd like it to be. 

RFC 4180 describes a "valid CSV" that is ideal, but does not reflect reality, and therefore most CSV parsers in most languages (and software such as Excel) have a much wider net in terms of what they can parse as CSV. We take this approach with our product as well.

Yes, we prefer the original data, and as a rule, we do optimise for the humans feeding that data to the software, and do our best to let the software work out delimiters and encodings and anything else that non-technical users do not understand.

As well as delimiter info, OpenSpending FDPs feature file encoding information that can be used by other systems such as linked pipes.

**Comment by jakubklimek** [comment]
@pwalsh I see your point, even though it would still make more sense to me if OS transcoded other CSV file formats to the RFC compatible, UTF-8 encoded, " quoted and comma delimited CSV on input and work with one format throughout the system.
@marek-dudas Please specify what CSV parsing library you use in your component and take a look at the implemenation of the standard [Tabular ](https://github.com/linkedpipes/etl/tree/master/plugins/t-tabular)component in LP-ETL which handles all these settings. If the FDP descriptors indeed contain these parameters, it should not be a problem to use them.

**Comment by akariv** [comment]
Just to add my 2 cents - Excel, the most widely used spreadsheet application does not produce UTF-8 encoded files (nor parse such files).
As most of our government partners (as well as citizens) work with Excel, standard conformance makes little sense to the actual users of the platform (unfortunately). Many of them would prefer that OS provided a non-standard CSV file that Excel might open correctly than getting a standard CSV file which looks like gibberish.

**Comment by marek-dudas** [comment]
Ok, I am not arguing. I am using the "Super CSV" library, should be the same one as in Tabular LP component, so it should be easy to add delimiter configuration based on the one specified in uploaded FDP descriptor.

**Comment by marek-dudas** [comment]
So, the delimiter (together with quoteChar) configuration is now implemented in the latest commit. Extra columns in the CSV undescribed in the JSON also should not be a problem. I will try to implement also the support of various decimal marks.

**Comment by pwalsh** [comment]
@marek-dudas is there a test suite that provides a basic sanity check for the core functionality of this library? Concerned about the very inefficient feedback loop we have here which requires manual validation. Even fairly light coverage with 5-10 unit tests covering critical path parser and conversion functionality would be a huge help.

**Comment by marek-dudas** [comment]
I have now also implemented parsing different number formats (variable decimal marks and group separators) as defined in descriptor for the measure values. Will let you know when it is deployed on Fraunhofer server for further testing.

@pwalsh Sorry I apparently missed your last comment. Did you mean a test suite for the SuperCSV library itself? Or a test suite for the whole pipeline? I have a set of about ten test datasets which I rerun after each implementation. I agree that some automated tests would be nice. Do you have something like that for OpenSpending tools (with respect to testing loading of FDP packages) that I could look at?
