### ISSUE TITLE
HTTP Get List returns HTTP 505

### ISSUE THREAD

**Issue by fathoni** [openbudgets/pipeline-fragments#15]
Hi @marek-dudas ,

I was testing the FDP2RDF pipeline and noticed that there is an error upon executing HTTP Get List component. The component returns 505 HTTP Error.

The executed pipeline is located here:
http://localhost:8181/#/pipelines/edit/canvas?pipeline=http:%2F%2Flocalhost:8181%2Fresources%2Fpipelines%2Fcreated-1479718165609&execution=http:%2F%2Flocalhost:8181%2Fresources%2Fexecutions%2F5bffc8b8-e4e1-437d-9a23-7f2edb6d2cd1

This can be a LinkedPipes issue instead of FDP2RDF issue. Anyway, could you please have a look?

**Comment by marek-dudas** [comment]
I will look into it tomorrow morning, thanks for reporting.

**Comment by marek-dudas** [comment]
So one problem is that the path property of the resource in the datapackage.jsonld contains a space and the pipeline expects it to be URL encoded. A quick fix is URL-encoding the path manually in the descriptor, meanwhile, I will update the pipeline to do so automatically - there is probably no reason why not to do so.

**Comment by jindrichmynarz** [comment]
You probably don't want to URL-encode automatically in order to avoid double encoding. An example in JavaScript:

```js
encodeURIComponent(" ")
// "%20"
encodeURIComponent(encodeURIComponent(" "))
// "%2520"
```

This is an error in the source JSON descriptor not properly encoding URLs and it should be resolved there.

**Comment by pwalsh** [comment]
@fathoni can you please share your descriptor file.

**Comment by fathoni** [comment]
@pwalsh It is available here: https://s3.amazonaws.com/datastore.openspending.org/848b8e447d0dfc798a77ef4f3a7bbcbd/aragon-budget-expenditure-2007/datapackage.json

**Comment by marek-dudas** [comment]
Since the FDP (or the DP) spec says there can be a "relative unix-style path" or fully qualified URL, maybe I could url-encode only in case the path does not start with "http://". Or should I keep the current approach which simply assumes the path is already url-encoded?

**Comment by fathoni** [comment]
+1 for this 

>  I could url-encode only in case the path does not start with "http://".

**Comment by jindrichmynarz** [comment]
While the [Data Packages spec](http://specs.frictionlessdata.io/data-packages/#data-in-files-path) is not explicit about the supported kinds of absolute URLs, I think it's reasonable to assume that only absolute URLs starting with `(ht|f)tps?://` are expected.

**Comment by marek-dudas** [comment]
So I added url-encoding for non-URL values, as proposed by @jindrichmynarz. Will test it again when it is deployed on Fraunhofer server and then we can probably close this issue?

**Comment by fathoni** [comment]
sure @marek-dudas , thanks for the updates.

**Comment by jindrichmynarz** [comment]
I think it would be easiest just to nick the code from OpenSpending that concatenates and resolves file paths in Data Packages. @pwalsh, can you please point us in its direction? I think you must have already resolved the escaping problems, along with other issues that we haven't thought of yet.

**Comment by pwalsh** [comment]
@akariv see above can you please help out here.
