### ISSUE TITLE
incorrect property qb:dataset

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/pipeline-fragments#16]
Datasets produced by FDPtoRDF pipeline produce invalid property for observations. 
```
qb:dataset <http://data.openbudgets.eu/resource/dataset/thessaloniki> .
```

whilst should be 
```
qb:dataSet
```

**Comment by marek-dudas** [comment]
Thanks, it should be fixed now. Will let you know when it is updated on the Fraunhofer server for further testing.
