### ISSUE TITLE
DCV validation pipeline fragment returns empty report

### ISSUE THREAD

**Issue by marek-dudas** [openbudgets/pipeline-fragments#2]
After fixing some errors, the pipeline final mustache generated report is empty. Might be error on my side or does it just mean that no errors were detected?

Link to the execution: http://obeu.vse.cz:9080/#/executions/detail?execution=http:%2F%2Fobeu.vse.cz:9080%2Fresources%2Fexecutions%2Fd9cbcd85-be7e-4079-94ce-5da03f073f2f

**Comment by jindrichmynarz** [comment]
It seems that no constraint violations were found in this case. However, the report should not be empty.

**Comment by jindrichmynarz** [comment]
@marek-dudas, did linkedpipes/etl#152 solve this issue?

**Comment by marek-dudas** [comment]
Cannot tell, I am now getting 

SPARQL construct - IC-20
Root cause: Not a valid (absolute) IRI:

Is that error at my side?
The pipeline is here http://obeu.vse.cz:9080/#/pipelines/edit/canvas?pipeline=http:%2F%2Fobeu.vse.cz:9080%2Fresources%2Fpipelines%2Fcreated-1464533644942&execution=http:%2F%2Fobeu.vse.cz:9080%2Fresources%2Fexecutions%2F15e3c7fd-07ec-418d-877c-6c93626e9f0c

**Comment by jindrichmynarz** [comment]
This is an error in the pipeline fragment that was created as a side effect of linkedpipes/etl#152. c34aa6f1bf70903d80b79ce3f8a2a531c2fae15a fixes this error.
