### ISSUE TITLE
FDP to RDF: where's the output?

### ISSUE THREAD

**Issue by johanricher** [openbudgets/pipeline-fragments#22]
I'm using the SaaS version on next.openspending.com. I just imported a dataset and now would like to convert to RDF using the pipeline.

I tried the "Run external hooks" button on the OS Admin page but nothing happened. The [OBEU tutorial](https://github.com/openbudgets/pipeline-fragments/tree/master/FDPtoRDF/documentation/user%20documentation) says that "the dataset will be available in the OpenBudgets platform." but doesn't explain what is the "OpenBudgets platform" and where the output of the ETL is.

**Comment by marek-dudas** [comment]
I assume the dataset should ideally appear at http://eis-openbudgets.iais.fraunhofer.de/explorer/ in a few minutes after clicking the "Run external hooks". There is no feedback implemented yet, so it actually looks like "nothing happened". A fix is planned.
The pipeline was being updated to a new version recently and I am not sure if everything is working yet - maybe @liyakun or @HimmelStein know more about that.

**Comment by johanricher** [comment]
Thanks for the swift response @marek-dudas. Unfortunately the dataset is not appearing there. I tried to run external hooks several times. I imagine it should also appear [here](https://github.com/openbudgets/datasets), right?

Thanks! And btw If this issue should be posted elsewhere please let me know.

**Comment by marek-dudas** [comment]
The github "datasets" repository is AFAIK only for manually created datasets. Posting here is fine.
To speed-up solving the issue, if you could send me the FDP datapackage from openspending, I could try running the pipeline locally and see if there is any problem in the transformation itself. There should be an option to download the datapackage somewhere near the "run external hooks" button.

**Comment by johanricher** [comment]
Great! [Here's the package straight from OS](https://s3.amazonaws.com/datastore.openspending.org/74ad33ef9a3354fe679b79fe4accff12/budget_mairie18/datapackage.json).

**Comment by marek-dudas** [comment]
So there was a bug in the pipeline (one missing check for empty values). I have fixed it, but the pipeline needs to be updated on the server (I cannot do that myself). I will let you know here when its done and we test again. Thanks for reporting this!

**Comment by johanricher** [comment]
Thanks for fixing it! :)

**Comment by johanricher** [comment]
@marek-dudas Hi, any news on the update? Do you have any idea when this will be put into production?

**Comment by fathoni** [comment]
hi, @marek-dudas , the pipeline has been updated by @lavdim , and I tested this using Madrid dataset - [here](https://next.openspending.org/viewer/848b8e447d0dfc798a77ef4f3a7bbcbd:madrid-testing) is the OS package link. After running the hook for this dataset, I can find two results when I search "Madrid" in the packager. However, the result is not clickable to see further details. Is there anything missing from our side? Or could it be fixed from the FDP2RDF pipeline?

**Comment by marek-dudas** [comment]
Thanks @fathoni . If you mean the result is not clickable in OS-Explorer, it is probably related to this [issue with OS-Explorer/Rudolf](https://github.com/openbudgets/platform/issues/35) - which is waiting for the decision what to do with it.

**Comment by marek-dudas** [comment]
After a long time and a lot of development, including moving from next.openspending.org to an altered version of data upload at http://apps.openbudgets.eu/packager, I think the original problem discussed here is more-or-less solved.
