### ISSUE TITLE
possible typo in obeu-model-integrity-constraints

### ISSUE THREAD

**Issue by marek-dudas** [openbudgets/pipeline-fragments#26]
There seems to be a typo ```?deprectedTerm``` in the "Use of deprecated term" SPARQL endpoint DPU in the pipeline. @jindrichmynarz better if you could check and fix, I don't want to be responsible for introducing another bug doing it myself.

**Comment by jindrichmynarz** [comment]
You're exactly right. There's a typo in this integrity constraint. Now fixed.
