### ISSUE TITLE
FDPtoRDF incorrectly creating observations in case of multiple measures

### ISSUE THREAD

**Issue by marek-dudas** [openbudgets/pipeline-fragments#7]
@marek-dudas @mlukasch we run the pipeline (v0.2.6) with the ESIF sample dataset https://github.com/openbudgets/pipeline-fragments/blob/master/FDPtoRDF/test/test1/datapackage.jsonld , which contains three amount columns (EU amount, national amount, and total amount). The RDF results can be seen at the Fuseki server. 
The pipeline treats the original csv files as three tables, each has one of the three amount values. The four rows of the three tables are named b0, b1, b2, b3. We do not know which amount is associated with which table. e.g. 
"b1" , "http://data.openbudgets.eu/ontology/dsd/measure/amount" , "319794.6" ,
"b1", "http://data.openbudgets.eu/ontology/dsd/measure/amount" , "310196.35" ,
"b1" , "http://data.openbudgets.eu/ontology/dsd/measure/amount" , "629990.95" ,
All these rows shall have a unique name. for example, b0 - b3, b4 - b7, b8-11. 
AT-AT-AT as the value of the administrator dimension. one AT would be enough. 
do I understand correctly?

**Comment by marek-dudas** [comment]
Should be solved now: the pipeline creates separate property for each measure. Based on previous discussions, the former approach creating a separate dataset for each measure was dropped.

**Comment by jindrichmynarz** [comment]
Does the pipeline use the multi-measure approach with `qb:measureType`?

**Comment by marek-dudas** [comment]
No, it uses "the one supported by the SDMX information model" (as called in the documentation) - it suits the FDP situation better, since all attribute and dimension values are the same for all measures in one source 'row'. At least as far as I have seen. Now that I think about it, FDP could theoretically contain multiple measures that would require separate observations, or maybe even separate DCV datasets. But I would go with the current approach as it seems to be working properly so far and was very easy to implement. If it conforms to the OBEU format of course.

**Comment by jindrichmynarz** [comment]
> "This _measure dimension_ approach is the one supported by the SDMX information model."

The _measure dimension_ mentioned in the DCV specification is `qb:measureType`.

So I assume that the pipeline instead uses the approach of multiple measures per observation.

**Comment by marek-dudas** [comment]
Right, I misread the documentation now looking for the proper name definition (they call it "the first approach" and then explain the second one first...). Anyway, the implementation uses multiple measures per observation as you say.

**Comment by HimmelStein** [comment]
@marek-dudas great work!

**Comment by jindrichmynarz** [comment]
I think it is fine to start with this approach. Should we encounter any mismatches when mapping from FDP to this approach, we can reopen this issue.
